version: "3.6"
services:
# ----------------------------------------- Logion node 1 --------------------------------------------------------------
  node:
    image: logionnetwork/logion-node:${NODE_TAG:-latest}
    ports:
      - 127.0.0.1:9944:9944
    environment:
      - NODE_KEY=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - CUSTOM_OPTIONS=--alice --no-mdns --ws-external --rpc-cors all
      - CHAIN_SPEC=dev
